#!/data/data/com.termux/files/usr/bin/bash

#
#      Author: Ryuuou
#      Build date: 12 Mei 2022
#

###########################################################

# Mengidentifikasi ukuran layar ternux pengguna.
# Digunakan agar tampilan dari Dialog shell script
# sama dengan posisi kotak dialog yang telah disesuaikan.

###########################################################


function screen(){
    # Local variabel yang menyimpan nilai ukuran layar yang dibutuhkan.
    local COLUMNS_REQUIRED=79

    # Mengidentifikasi apakah environment COLUMNS ada atau tidak.
    if [[ -n $COLUMNS && -n $LINES ]]; then
        # Program akan berjalan jika ukuran layar pengguna sama dengan ukuran
layar yang dibutuhkan.
        if (( $COLUMNS >= $COLUMNS_REQUIRED )); then
            true
        else
            # Jika ukuran layar lebih kecil dari ukuran layar yang dibutuhkan
maka akan menjalankan kondisi ini.
            if (( $COLUMNS <= $COLUMNS_REQUIRED )); then
                dialog \
                --infobox "$show_screensizeUser $COLUMNS
                $show_screensizeRequired $COLUMNS_REQUIRED $show_screensizeZoo
mIn" 9 0
            fi
            exit 1
        fi
    else
        # Pengguna akan di minta untuk memasukan COLUMNS & LINES kedalam envir
onment
        printf $show_screensizeAlert
        exit 1
    fi
}
